@startuml
skinparam monochrome true
class SistemaGamificacao <<Controle>> {
    +calcularBonus()
}
class Aluno <<Entidade>> {
    +pontos : int
    +moedas : int
}
SistemaGamificacao ..> Aluno : credita
@enduml
