@startuml
skinparam monochrome true
autonumber
participant S as ":Sistema"
participant G as ":SistemaGamificacao"
participant A as ":Aluno"
S -> G : concluirTarefa()
G -> G : calcular()
G -> A : creditarXP(100)
G --/ S : Ok
@enduml
