@startuml
skinparam monochrome true
autonumber
actor "Usuário (Ator)" as U
participant ":ServicoAutenticacao" as C
U -> C : login(email, senha)
activate C
C -> C : validarCredenciais()
C --/ U : Resultado (Sucesso/Erro)
deactivate C
@enduml
