@startuml
skinparam monochrome true
autonumber
participant T as ":Tutor"
participant D as ":PainelVisual"
participant A as ":Aluno"
T -> D : visualizar(id)
activate D
D -> A : obterMetricas()
A --/ D : dados
D --/ T : Relatório Visual
deactivate D
@enduml
