@startuml
skinparam monochrome true
autonumber
participant A as ":Aluno"
participant E as ":Editor"
participant F as ":Flashcard_SM2"
A -> E : entrada(p, r)
E -> F : <<create>>(p, r)
F --/ A : Sucesso
@enduml
