@startuml
skinparam monochrome true
autonumber
participant V as ":Visitante"
participant C as ":ControladorAutenticacao"
participant A as ":MD_Alunos"
V -> C : registrar(dados)
activate C
C --/ A : <<create>>
activate A
A -> A : inicializarPerfil()
deactivate A
C --/ V : Cadastro Confirmado
deactivate C
@enduml
