@startuml
skinparam monochrome true
class MD_Simulado <<Entidade>> {
    +tempoRestante : int
    +iniciarTeste()
}
class Questao <<Entidade>> {
    +texto : string
}
MD_Simulado "1" *-- "*" Questao
@enduml
