@startuml
skinparam monochrome true
autonumber
participant U as ":Usuario"
participant P as ":PainelConfiguracao"
participant A as ":Acessibilidade"
U -> P : selecionarOpcao()
P -> A : salvar()
A --/ P : ok
@enduml
