@startuml
skinparam monochrome true
class MD_Alunos <<Entidade>> {
    +definirFaseInicial(nota : float)
}
class MD_Simulado <<Entidade>> {
    +nota : float
    +iniciarTeste()
}
MD_Alunos --> MD_Simulado : realiza
@enduml
