@startuml
skinparam monochrome true
class MD_Tutor {
    +gerenciarConteudo()
}
class MD_Modulos <<Entidade>> {
    +nomeModulo : string
}
class MD_Flashcards <<Entidade>>
MD_Modulos *-- MD_Flashcards
@enduml
