@startuml
skinparam monochrome true
class MD_Tutor {
    +acompanharDesempenho()
}
class MD_Alunos <<Entidade>> {
    +progresso : float
}
class PainelVisual <<Fronteira>> {
    +renderizar()
}
MD_Tutor ..> MD_Alunos : visualiza
@enduml
