@startuml
skinparam monochrome true
autonumber
participant IA as ":AgenteIA"
participant T as ":MD_Tutor"
participant Al as ":Aluno"
IA -> IA : detectarComplexidade()
IA -> T : escalar(duvida, id)
T --/ Al : Resposta
@enduml
