@startuml
skinparam monochrome true
class AgenteIA <<Controle>> {
    +responder(pergunta)
}
class MD_Duvidas <<Entidade>> {
    -pergunta : string
    -resposta : string
}
AgenteIA ..> MD_Duvidas : consulta
@enduml
