@startuml
skinparam monochrome true
class MD_MotorSM2 <<Controle>> {
    +aplicarSM2(feedback)
}
class MD_Flashcards <<Entidade>> {
    +proximaRevisao : date
}
MD_MotorSM2 --> MD_Flashcards : atualiza
@enduml
