@startuml
skinparam monochrome true
autonumber
participant M as ":GerenciadorProgresso"
participant A as ":MD_Alunos"
participant F as ":MD_Fases"
M -> A : obterProgresso()
M -> F : desbloquear()
F --/ M : Sucesso
@enduml
