@startuml
skinparam monochrome true
class MD_Fases <<Entidade>> {
    -bloqueada : bool
    +desbloquear()
}
class MD_Alunos <<Entidade>> {
    -progresso : float
}
MD_Fases ..> MD_Alunos : verifica
@enduml
